---
abstract: 'A Simple totally OO CGI interface that is CGI.pm compliant'
author:
  - 'Andy Armstrong <andy@hexten.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Simple
no_index:
  directory:
    - t
    - inc
requires:
  IO::Scalar: '0'
  Test::More: '0'
version: '1.115'
