---
name: CGI-Simple
version: 1.107
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: A Simple totally OO CGI interface that is CGI.pm compliant
license: perl
resources:
  license: ~
requires:
  Test::More: 0
provides:
  CGI::Simple:
    file: lib/CGI/Simple.pm
    version: 1.107
  CGI::Simple::Cookie:
    file: lib/CGI/Simple/Cookie.pm
    version: 1.107
  CGI::Simple::Standard:
    file: lib/CGI/Simple/Standard.pm
    version: 1.107
  CGI::Simple::Util:
    file: lib/CGI/Simple/Util.pm
    version: 1.107
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
